### ISSUE TITLE
MongoDB issue

### ISSUE THREAD

**Issue by JessieKr** [Alheimsins/bigfive-web#229]
Hello. I **can't log in** and **collect data** from the test.

- [NodeJS installed]
- [NextJS installed] as  _bigfive-web\node_modules\next_
- [Micro installed] as _bigfive-web\node_modules\micro_
- [MongoDB intalled]
- [Docker installed ] 

When I tried to complete command "**vim config.js**" it **hasn't worked**. With the message "undefined command"
Next, I go through to the localhost:3000 and visually website works fine but login and result don't work.
What I should do with that? My MongoDB Compass application has localhost:27017 and works with a blank authentication. I may have installed it all, but so inexperienced and without certain knowledge that I cannot figure it out.
https://imgur.com/a/G35xEwl

**Comment by zrrrzzt** [comment]
Hi there :-) Thank you for your interest in our project.

Let's see if you can help you.

`$ vim config.js` will only work if you have `vim` installed. This is not necessary because you can edit config.js with any text editor.

Can you please explain further what you mean by `result don't` work?
From your image it looks like there is a test saved in the results collection. If you look at that one you should be able to view the result of your test by visiting `${url}/result/${_id}` so if you run this on your localhost and the `_id` is `58a70606a835c400c8b38e84` the result url would be `http://localhost:3000/result/58a70606a835c400c8b38e84`

`Login` does not work. Or to be presise: login brings you to the front page. I think it is a survivor from one of our previous iterations where you could login via Facebook or Twitter to save your results. It never made it to the new version. @maccyber might be the only one to know why we kept the link ;-)

**Comment by JessieKr** [comment]
Thank you a lot for your answer. When I completed the test it is didn't give the result.

**Comment by zrrrzzt** [comment]
Do you mind to try another test and take a look at the logs for errors?

You will typically have a log in the developer console for your browser and another on the local server.

**Comment by JessieKr** [comment]
I haven't know how to open your project via docker. On another resource I found instructions. Can you please say on which version your site had Login system?

**Comment by maccyber** [comment]
In the brach [with-login](https://github.com/Alheimsins/bigfive-web/tree/with-login).
I didn't finish the implementation, so can't support you there, but you can probably reuse some of the code in https://github.com/Alheimsins/bigfive-web/commit/8a90f23f847d866391a964f51aec89d04912d598
